config/routes.rb
Brimir::Application.routes.draw do

  devise_for :users

  resources :users

  resources :tickets, only: [:index, :show, :update, :new, :create]

  resources :labelings, only: [:destroy, :create]

  resources :rules

  resources :labels, only: [ :destroy, :update ]

  resources :replies, only: [:create, :new]
  get '/attachments/:id/:format' => 'attachments#show'

  root :to => 'tickets#index'

	namespace :api do
		namespace :v1 do
			resources :tickets, only: [ :index, :show ]
      resources :sessions, only: [ :create ]
		end
	end

end

app/models/ticket.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2014 Ivaldi http://ivaldi.nl
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class Ticket < ActiveRecord::Base
  include CreateFromUser

  validates_presence_of :user_id

  belongs_to :user
  belongs_to :assignee, class_name: 'User'

  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  has_many :notifications, as: :notifiable, dependent: :destroy
  has_many :notified_users, source: :user, through: :notifications

  has_many :status_changes

  enum status: [:open, :closed, :deleted, :waiting]
  enum priority: [:unknown, :low, :medium, :high]

  after_update :log_status_change
  after_create :create_status_change

  def self.active_labels(status)
    label_ids = where(status: Ticket.statuses[status])
        .joins(:labelings)
        .pluck(:label_id)
        .uniq

    return Label.where(id: label_ids)
  end

  scope :by_label_id, ->(label_id) {
    if label_id.to_i > 0
      joins(:labelings).where(labelings: { label_id: label_id })
    end
  }

  scope :by_status, ->(status) {
    where(status: Ticket.statuses[status.to_sym])
  }

  scope :filter_by_assignee_id, ->(assignee_id) {
    if !assignee_id.nil?
      if assignee_id.to_i == 0
        where(assignee_id: nil)
      else
        where(assignee_id: assignee_id)
      end
    else
      all
    end
  }

  scope :search, ->(term) {
    if !term.nil?
      term = '%' + term.downcase + '%'
      where('LOWER(subject) LIKE ? OR LOWER(content) LIKE ?',
            term, term)
    end
  }

  scope :ordered, -> {
    order(:created_at).reverse_order
  }

  scope :viewable_by, ->(user) {
    if !user.agent?
      ticket_ids = Labeling.where(label_id: user.label_ids)
          .where(labelable_type: 'Ticket')
          .pluck(:labelable_id)
      where('tickets.id IN (?) OR tickets.user_id = ?', ticket_ids, user.id)
    end
  }

  def set_default_notifications!(created_by)

    # customer created ticket for another user
    if !created_by.agent? && created_by != user
      self.notified_user_ids = User.agents_to_notify.pluck(:id)
      self.notified_user_ids << user.id

    # ticket created by customer
    elsif !created_by.agent?
      self.notified_user_ids = User.agents_to_notify.pluck(:id)

    # ticket created by agent for another user
    elsif created_by.agent? && created_by != user
      self.notified_user_ids = [user.id]

    # agent created ticket for himself
    else
      self.notified_user_ids = []
    end
  end

  def status_times
    total = {}

    Ticket.statuses.keys.each do |key|
      total[key.to_sym] = 0
    end

    status_changes.each do |status_change|
      total[status_change.status.to_sym] += status_change.updated_at - status_change.created_at
    end

    # add the current status as well
    current = status_changes.ordered.last
    unless current.nil?
      total[current.status.to_sym] += Time.now - current.created_at
    end

    Ticket.statuses.keys.each do |key|
      total[key.to_sym] /= 1.minute
    end

    total
  end

  protected
    def create_status_change
      status_changes.create! status: self.status
    end

    def log_status_change

      if self.changed.include? 'status'
        previous = status_changes.ordered.last

        unless previous.nil?
          previous.updated_at = Time.now
          previous.save
        end

        status_changes.create! status: self.status
      end
    end

end

app/controllers/api/v1/tickets_controller.rb
 # Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2014 Ivaldi http://ivaldi.nl
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
class Api::V1::TicketsController < Api::V1::ApplicationController

	load_and_authorize_resource :ticket

	def index
		@tickets = Ticket.by_status(:open).viewable_by(current_user)
	end

	def show
		@ticket = Ticket.find(params[:id])
	end
end

app/controllers/tickets_controller.rb
# Brimir is a helpdesk system to handle email support requests.
# Copyright (C) 2012-2014 Ivaldi http://ivaldi.nl
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class TicketsController < ApplicationController

  before_filter :authenticate_user!, except: [:create, :new]
  load_and_authorize_resource :ticket, except: :create
  skip_authorization_check only: :create

  # this is needed for brimir integration in other sites
  before_filter :allow_cors, only: [:create, :new]

  def show
    @agents = User.agents

    @reply = @ticket.replies.new(user: current_user)
    @reply.set_default_notifications!

    @labeling = Labeling.new(labelable: @ticket)
  end

  def index
    @agents = User.agents

    params[:status] ||= 'open'

    @tickets = @tickets.by_status(params[:status])
      .search(params[:q])
      .by_label_id(params[:label_id])
      .filter_by_assignee_id(params[:assignee_id])
      .ordered

    respond_to do |format|
      format.html do
        @tickets = @tickets.page(params[:page])
      end
      format.csv do
        @tickets = @tickets.includes(:status_changes)
      end
    end
  end

  def update
    respond_to do |format|
      if @ticket.update_attributes(ticket_params)

        # assignee set and not same as user who modifies
        if !@ticket.assignee.nil? && @ticket.assignee.id != current_user.id

          if @ticket.previous_changes.include? :assignee_id
            TicketMailer.notify_assigned(@ticket).deliver

          elsif @ticket.previous_changes.include? :status
            TicketMailer.notify_status_changed(@ticket).deliver

          elsif @ticket.previous_changes.include? :priority
            TicketMailer.notify_priority_changed(@ticket).deliver
          end

        end

        format.html {
          redirect_to @ticket, notice: I18n::translate(:ticket_updated)
        }
        format.js {
          render notice: I18n::translate(:ticket_updated)
        }
        format.json {
          head :no_content
        }
      else
        format.html {
          render action: 'edit'
        }
        format.json {
          render json: @ticket.errors, status: :unprocessable_entity
        }
      end
    end
  end

  def new
    unless current_user.blank?
      signature = { content: '<p></p>' + current_user.signature.to_s }
    else
      signature = {}
    end

    unless params[:ticket].nil? # prefill params given?
      @ticket = Ticket.new(signature.merge(ticket_params))
    else
      @ticket = Ticket.new(signature)
    end

    unless current_user.nil?
      @ticket.user = current_user
    end
  end

  def create
    if params[:format] == 'json'
      @ticket = TicketMailer.receive(params[:message])
    else
      @ticket = Ticket.new(ticket_params)
    end

    if @ticket.save

      if current_user.nil?
        user = @ticket.user
      else
        user = current_user
      end

      Rule.apply_all(@ticket)

      # where user notifications added?
      if @ticket.notified_users.count == 0
        @ticket.set_default_notifications!(user)
      end

      NotificationMailer.new_ticket(@ticket).deliver
    end

    respond_to do |format|
      format.html do

        if @ticket.valid?

          if current_user.nil?
            return render text: I18n::translate(:ticket_added)
          else
            redirect_to ticket_url(@ticket), notice: I18n::translate(:ticket_added)
          end

        else
          render 'new'
        end

      end

      format.json do
        render json: @ticket, status: :created
      end

      format.js { render }
    end
  end

  protected
    def ticket_params
      if !current_user.nil? && current_user.agent?
        params.require(:ticket).permit(
            :to_date,
	    :fname,
            :from,
            :content,
            :subject,
            :status,
            :assignee_id,
            :priority,
            :message_id)
      else
        params.require(:ticket).permit(
            :to_date,
            :from,
            :content,
            :subject,
            :priority)
      end
    end

    def allow_cors
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'GET,POST'
      headers['Access-Control-Allow-Headers'] =
          %w{Origin Accept Content-Type X-Requested-With X-CSRF-Token}.join(',')

      head :ok if request.request_method == 'OPTIONS'
    end

end

app/views/tickets/_change_assignee_form.html.erb
<div id="change-assignee" class="reveal-modal small" data-reveal>
  <h3><%= t(:change_assignee) %></h3>

  <%= form_for ticket, remote: true, method: :patch do |f| %>
    <p>
	<% if ticket.assignee_id.nil? %>
    	    <%= f.select :assignee_id, options_from_collection_for_select(@agents, 'id', 'fname', ticket.assignee_id), { include_blank: t(:employee_not_select) }, { class: 'select2' } %>
    	<% else %>
    	    <%= f.select :assignee_id, options_from_collection_for_select(@agents, 'id', 'fname', ticket.assignee_id), { include_blank: t(:unassigned) }, { class: 'select2' } %>
    	<% end %>
    </p>
    <%= f.submit t(:assign), class: 'button' %>
  <% end %>

  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/tickets/_change_assignee_time.html.erb
<div id="change-assignee-time" class="reveal-modal small" data-reveal>
  <h3><%= t(:time_assignee) %></h3>

  <%= form_for ticket, remote: true, method: :patch do |f| %>
    <p>
    	    <%= f.text_field :to_date, label: false, id: 'datetimepicker' %>
    </p>
    <%= f.submit t(:time_assign), class: 'button' %>
  <% end %>

  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/tickets/_form.html.erb
<%= form_for @ticket, url: tickets_url, html: { multipart: true } do |f| %>

  <h3><%= t(:new_ticket) %></h3>
  <p>
    <label><%= t(:fname) %></label>
    <%= f.autocomplete_field :fname, users_path, id: 'from_fullname', id_element: '#id'   %>
  </p>
  <p>
    <%= f.text_field :from %>
  </p>
  <p>
    <%= f.text_field :subject %>
  </p>
  <p>
    <%= f.text_area :content, class: 'tinymce' %>
  </p>
  <p>
    <%= f.submit class: 'button regular radius', value: t(:create_ticket) %>
  </p>

<% end %>

<script>
window.onload = function() { 
$('#from_fullname').bind('railsAutocomplete.select', function(event, data){
    if ((data.item.id) != null)
    {
	$("#ticket_from").val(data.item.id);
    } else {
	$("#ticket_from").val(randomEmail(8) + '@' + randomEmail(8) + '.com');
    }
});

function randomEmail (strLength) {
    var result = [];
    charSet = 'abcdefghijklmnopqrstuvwxyz';
        
        while (--strLength) {
        result.push(charSet.charAt(Math.floor(Math.random() * charSet.length)));
        }
                        
    return result.join('');
}

};
</script>

app/views/tickets/_priority_dropdown.html.erb
<ul id="priorities-<%= ticket.id %>" class="f-dropdown" data-dropdown-content>
  <% Ticket.priorities.keys.each do |value| %>
    <li>
      <%= link_to ticket_path(ticket, ticket: { priority: value }, short: short),
          method: :patch, remote: true do %>
        <span class="priority-<%= value %> fa fa-fw fa-circle"></span>
        <%= t(value) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/tickets/_status_dropdown.html.erb
<ul id="statuses-<%= ticket.id %>" class="f-dropdown" data-dropdown-content>
  <% Ticket.statuses.keys.each do |value| %>
    <li>
      <%= link_to ticket_path(ticket, ticket: { status: value }),
          method: :patch, remote: true do %>

        <span class="fa fa-fw fa-<%= status_icon(value) %>"></span>
        <%= t(value) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/tickets/index.csv.erb
<%-
  header = [
    'Id',
    t(:subject, scope: 'activerecord.attributes.ticket'),
    t(:priority, scope: 'activerecord.attributes.ticket'),
    t(:status, scope: 'activerecord.attributes.ticket'),
    t(:assignee_id, scope: 'activerecord.attributes.ticket'),
    "#{t(:open)} (#{t(:minutes)})",
    "#{t(:waiting)} (#{t(:minutes)})",
    "#{t(:closed)} (#{t(:minutes)})",
    "#{t(:deleted)} (#{t(:minutes)})",
  ]

  rows = []

  @tickets.each do |ticket|
    status_times = ticket.status_times
    rows << [
        ticket.id,
        '"' + ticket.subject.gsub(/"/, '""') + '"',
        t(ticket.priority),
        t(ticket.status),
        (ticket.assignee.email unless ticket.assignee.nil?),
        status_times[:open].round(1),
        status_times[:waiting].round(1),
        status_times[:closed].round(1),
        status_times[:deleted].round(1)
    ]
  end
-%>
<%= header.join(',') %>
<%- rows.each do |row| -%>
<%= row.join(',').html_safe %>
<%- end -%>

app/views/tickets/index.html.erb
<% @unassigned = false %>
<div class="panel">
  <div class="row collapse">
    <div class="medium-9 columns">
      <h4 class="filter-title no-m pts">

        <%# if params[:q].present? %>
          <%#= t(:count_tickets_containing, count: @tickets.count) %> <em><%#= params[:q].to_s %></em>
        <%# else %>
          <%#= t(:count_tickets, count: @tickets.count) %>
        <%# end %>

      </h4>
    </div>
    <div class="medium-3 columns">
      <%= form_tag tickets_path, method: :get do %>
        <%= hidden_field_tag(:assignee_id, params[:assignee_id]) unless params[:assignee_id].blank? %>
        <%= hidden_field_tag :status, params[:status] %>
        <div class="row collapse">
          <div class="small-8 columns">
            <%= text_field_tag :q, params[:q], class: 'no-m' %>
          </div>
          <div class="small-4 columns">
            <%= button_tag t(:search), type: 'submit', class: 'radius no-m button postfix' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<table class="full zebra">
  <thead>
    <tr>
      <th class="nowrap text-left text-secondary"><%=t(:number_ticket) %></th> 
      <th class="nowrap text-left text-secondary"><%=t(:prio_ticket) %></th> 
      <th class="nowrap text-left text-secondary"><%=t(:initiator) %></th> 
      <th class="nowrap text-left text-secondary"><%=t(:context) %></th> 
      <th class="nowrap text-left text-secondary"><%=t(:assigned_to) %></th> 
      <th class="nowrap text-left text-secondary"><%=t(:create_date) %></th> 
      <th class="nowrap text-left text-secondary"><%=t(:to_date) %></th> 
    </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
      <tr data-ticket-url="<%= ticket_url(ticket) %>">

        <td class="nowrap text-center">
          <% if !ticket.id.nil? %>
	    #<%=  ticket.id %>
          <% end %>
        </td>

        <td class="nowrap text-left">
          <% if can? :update, ticket %>
            <a href="#" data-dropdown="priorities-<%= ticket.id %>">
              <span class="priority-<%= ticket.priority %> fa fa-circle"></span>
            </a>
            <%= render 'priority_dropdown', ticket: ticket, short: true %>
          <% else %>
            <span class="priority-<%= ticket.priority %> fa fa-circle"></span>
          <% end %>
        </td>

        <td class="nowrap text-left">
	  <% if !ticket.user.email.nil? %>
	    <% if ticket.user.fname.nil? %>
	      <%= t(:undefine) %>
	    <% else %>
	      <%= ticket.user.fname %>
	    <% end %>
          <% else %>
            <%= t(:delete) %>
          <% end %>
        </td>

        <td class="text-secondary table-nowrap text-left">
          <% ticket.labels.viewable_by(current_user).each do |label| %>
            <%= render label %>
          <% end %>
          <% if !ticket.subject.nil? %>
            <a href="<%= ticket_url(ticket) %>">
              <% if ticket.replies.size > 0 %>
                <span class="success radius label" title="<%= ticket.replies.size %> <%= t(:replies) %>"><%= ticket.replies.size %></span>
              <% end %>
              <%= ticket.subject %><!-- <span class="text-secondary"><%= sanitize(ticket.content, tags: [])[0..80].html_safe %></span> -->
            </a>
          <% else %>
            <%= link_to ticket do %>
              <em>(<%= t(:no_subject) %>)</em>
            <% end %>
          <% end %>
        </td>

        <td class="nowrap text-left">
          <% if can? :update, ticket %>
            <% if ticket.assignee %>
              <a data-assignee-id="<%= ticket.assignee.id %>" href="#"><i class="fa fa-user"></i> <%= ticket.assignee.fname %></a>
            <% else %>
              <a data-assignee-id="" href="#"><em><%= t(:unassigned) %></em></a>
              <% @unassigned = true %>
            <% end %>
          <% else %>
            <% if ticket.assignee %>
              <i class="fa fa-user"></i> <%= ticket.assignee.fname %>
            <% else %>
              <em><%= t(:unassigned) %></em>
            <% end %>
          <% end %>
        </td>

        <td class="nowrap text-left">
          <%= l ticket.created_at, format: :short %>
        </td>

        <td class="nowrap text-left">
          <% if !ticket.to_date.nil? %>
            <%= l ticket.to_date, format: :short %>
          <% else %>
            <%= t(:untime) %>
          <% end %>
        </td>

      </tr>
    <% end %>

    <% if @tickets.empty? %>
      <tr>
        <td colspan="100%"><%= t(:no_tickets_found) %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<% if @unassigned == true %>
  <script>
  window.onload = function() { showStickyNoticeToast.call() };
  </script>
<% end %>

<% unless @tickets.empty? %>

  <div class="row">
    <div class="small-6 columns">
      <%= will_paginate @tickets %>
    </div>
    <div class="small-6 columns">
      <%= link_to tickets_path(params.merge(format: :csv)), class: 'tiny secondary radius button right' do %>
        <%= t(:export_tickets) %>
      <% end %>
    </div>
  </div>

  <%= render 'change_assignee_form', { ticket: Ticket.new } %>

<% end %>

app/views/tickets/new.html.erb
<div class="row">
  <div class="medium-9 columns">

    <%= render 'form' %>

  </div>
</div>

app/views/tickets/show.html.erb
<div class="row" style="border-bottom: 1px solid #bec8dc">
  <div class="medium-12 columns">
    <h3 class="mt">
      <%= !@ticket.subject.nil? ? @ticket.subject : '<em>(' + t(:no_subject) + ')</em>'.html_safe %>
    </h3>
    <h5 class="subheader text-secondary mb">
      <div><%= t(:ticket_number) %> <strong><%= @ticket.id %></strong></div>
      <div><%= t(:ticket_by_at, email: @ticket.user.fname, at: l(@ticket.created_at, format: :long)) %></div>
    </h5>
  </div>
</div>

<div class="row collapse">
  <div class="medium-9 columns" style="border-right: 1px solid #bec8dc">
    <div class="ma">
      <% if @ticket.content.blank? %>
        (<%= t(:no_content) %>)
      <% else %>

        <div class="output">
          <% if @ticket.content_type == 'html' %>
            <% content = @ticket.content %>
          <% else %>
            <% content = text_to_html(@ticket.content) %>
          <% end %>

          <%= sanitize_html(content) %>
        </div>
      <% end %>

      <ul class="inline-list text-secondary">
        <% if !@ticket.notified_users.empty? %>
          <li><%= t(:notification_sent_to) %></li>
          <% @ticket.notified_users.each do |user| %>
            <li><%= user.email %></li>
          <% end %>
        <% end %>
      </ul>

      <% if @ticket.attachments.size > 0 %>
        <hr />
        <ul class="attachments>
          <%= render @ticket.attachments %>
        </ul>
      <% end %>
    </div>


    <% if @ticket.replies.size > 1 %>
      <div class="row replies">
        <div class="large-11 columns large-centered">
          <h3 class="mt"><%#= t(:num_replies, count: (@ticket.replies.size - 1)) %></h3>
          <ul>

            <% count = 0 %>
            <% @ticket.replies.chronologically.each do |reply| %>

              <%# minus 2, because @reply is a new ticket that is counted as well... %>
              <% if @ticket.replies.size - 2 == count %>
                <% div_class = 'content active' %>
              <% else %>
                <% div_class = 'content' %>
              <% end %>

              <%= render reply, div_class: div_class %>

              <% count += 1 %>

            <% end %>

          </ul>
        </div>
      </div>
    <% end %>

    <% if can? :create, @reply %>
      <%= render 'replies/form' %>
    <% end %>

  </div>

  <div class="medium-3 columns">
    <div class="ma">
      <dl class="sticky">
        <dt><%= t(:status) %></dt>

        <dd>
          <% if can? :update, @ticket %>
            <a href="#" data-dropdown="statuses-<%= @ticket.id %>">
              <span class="fa fa-fw fa-<%= status_icon(@ticket.status) %>"></span>
              <%= t(@ticket.status) %>
            </a>
            <%= render 'status_dropdown', ticket: @ticket %>
          <% else %>
            <span class="fa fa-fw fa-<%= status_icon(@ticket.status) %>"></span>
            <%= t(@ticket.status) %>
          <% end %>
        </dd>

        <dt><%= t(:priority) %></dt>
        <dd>
          <% if can? :update, @ticket %>
            <% if @ticket.user.id == @current_user.id || @current_user.tech? %>
              <a href="#" data-dropdown="priorities-<%= @ticket.id %>">
                <span class="priority-<%= @ticket.priority %> fa fa-fw fa-circle"></span>
                <%= t(@ticket.priority) %>
              </a>
              <%= render 'priority_dropdown', ticket: @ticket, short: false %>
            <% else %>
              <span class="priority-<%= @ticket.priority %> fa fa-fw fa-circle"></span>
              <%= t(@ticket.priority) %>
            <% end %>
          <% end %>
        </dd>

        <dt><%= t(:to_date) %></dt>
        <dd>
          <% if can? :update, @ticket %>
            <% if @ticket.user.id == @current_user.id || @current_user.tech? %>
              <% if !@ticket.to_date.nil? %>
                <span class="fa fa-fw fa-clock-o"></span>
                <a href="#" data-reveal-id="change-assignee-time">
                <%= l(@ticket.to_date, format: :long) %>
                </a>
              <% else %>
                <span class="fa fa-fw fa-clock-o"></span>
                <a href="#" data-reveal-id="change-assignee-time">
                <%= t(:untime) %>
                </a>
              <% end %>
            <% else %>
              <span class="fa fa-fw fa-clock-o"></span>
              <%= t(:untime) %>
            <% end %>
          <% end %>
        </dd>

        <dt><%= t(:employee) %></dt>
        <dd>
            <% if !@ticket.user.fname.nil? %>
              <span class="fa fa-fw fa-user"></span>
              <%= @ticket.user.fname %>
            <% end %>
        </dd>
  
        <% if !@ticket.user.department_role.nil? %>
          <dt><%= t(:department_role) %></dt>
          <dd>
            <span class="fa fa-fw fa-briefcase"></span>
            <%= @ticket.user.department_role %>
          </dd>
        <% end %>

        <% if !@ticket.user.department.nil? %>
          <dt><%= t(:department) %></dt>
          <dd>
            <span class="fa fa-fw fa-home"></span>
            <%= @ticket.user.department %>
          </dd>
        <% end %>

        <% if !@ticket.user.phone.nil? %>
          <dt><%= t(:phone) %></dt>
          <dd>
            <span class="fa fa-fw fa-phone"></span>
            <%= @ticket.user.phone %>
          </dd>
        <% end %>

        <% if !@ticket.user.email.empty? %>
          <dt><%= t(:email) %></dt>
          <dd>
            <span class="fa fa-fw fa-envelope"></span>
            <a class="url" href='mailto:<%= @ticket.user.email %>'><%= @ticket.user.email %></a>
          </dd>
        <% end %>

        <dt><%= t(:assignee) %></dt>
        <dd>
          <% if can? :update, @ticket %>
            <a href="#" data-reveal-id="change-assignee">
              <% if !@ticket.assignee %>
                <span class="fa fa-fw fa-user"></span>
                <%= t(:unassigned) %>
              <% else %>
                <span class="fa fa-fw fa-user"></span>
                <%= @ticket.assignee.fname %>
              <% end %>
            </a>
          <% else %>
            <% if !@ticket.assignee %>
              <span class="fa fa-fw fa-user"></span>
              <%= t(:unassigned) %>
            <% else %>
                <span class="fa fa-fw fa-user"></span>
                <%= @ticket.assignee.fname %>
            <% end %>
          <% end %>
        </dd>

        <dt><%= t(:labels) %></dt>
        <dd>
          <% if can? :update, @ticket %>
            <ul data-labelings="" style="margin-left: 0">
              <% @ticket.labelings.each do |labeling| %>
                <%= render labeling %>
              <% end %>
            </ul>
            <%= form_for @labeling, remote: true do |f| %>
              <%= f.hidden_field :labelable_id %>
              <%= f.hidden_field :labelable_type %>

              <div class="row collapse">
                <div class="small-9 columns">
                  <%= f.fields_for :label, Label.new do |f| %>
                    <%= f.text_field :name, label: false, placeholder: t(:label_name) %>
                  <% end %>
                </div>
                <div class="small-3 columns">
                  <%= f.button t(:add), type: 'submit', class: 'button postfix' %>
                </div>
              </div>
            <% end %>
          <% else %>
            <ul class="inline-list">
              <% @ticket.labels.viewable_by(current_user).each do |label| %>
                <li><%= render label %></li>
              <% end %>
            </ul>
          <% end %>
        </dd>
      </dl>
    </div>

  </div>

</div>

<%= render 'change_assignee_form', { ticket: @ticket } %>
<%= render 'change_assignee_time', { ticket: @ticket } %>

app/views/tickets/update.js.erb
<% if !params[:ticket][:status].blank? %>
  jQuery('[data-dropdown="statuses-<%= @ticket.id %>"]')
      .empty()
      .append('<span class="fa fa-<%= status_icon(@ticket.status) %>"></span> ' +
          '<%= j(t(@ticket.status)) %>');

<% elsif !params[:ticket][:priority].blank? %>
  jQuery('[data-dropdown="priorities-<%= @ticket.id %>"]')
      .empty()
      .append('<span class="priority-<%= @ticket.priority %> fa fa-circle"></span> ' +
          '<%= j(t(@ticket.priority)) unless params[:short] == 'true' %>');

<% else %>
  window.location.reload();
<% end %>

<%# close all dropdowns %>
var dropdowns = jQuery('.f-dropdown');
dropdowns.foundation('dropdown', 'close', dropdowns);