config/routes.rb
Brimir::Application.routes.draw do

  devise_for :users

  resources :users

  resources :tickets, only: [:index, :show, :update, :new, :create]

  resources :labelings, only: [:destroy, :create]

  resources :rules

  resources :labels, only: [ :destroy, :update ]

  resources :replies, only: [:create, :new]
  get '/attachments/:id/:format' => 'attachments#show'

  root :to => 'tickets#index'

	namespace :api do
		namespace :v1 do
			resources :tickets, only: [ :index, :show ]
      resources :sessions, only: [ :create ]
		end
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : 'RubyDesk' %></title>
    <%= favicon_link_tag 'favicon.png' %>
    <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic' %>
    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'jquery.toastmessage' %>
    <%= stylesheet_link_tag 'jquery.datetimepicker' %>
    <%= csrf_meta_tags %>
  </head>

  <body style="<%= 'background: #30363e' if user_signed_in? %>">

    <% if user_signed_in? %>
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1><a href="<%= root_path %>"><img src='/logo/logo.png'></a></h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <% if can? :manage, Rule %>
                <li><a href="<%= rules_path %>"><%= t(:rules) %></a></li>
            <% end %>
            <% if can? :manage, User %>
                <li><a href="<%= users_path %>"><%= t(:users) %></a></li>
            <% end %>
            <li class="has-dropdown">
              <a href="#"><%= current_user.fname %></a>
              <ul class="dropdown">
                <li>
                  <%= link_to edit_user_path(current_user) do %>
                    <i class="fa-cogs fa fa-fw"></i> <%= t(:personal_settings) %>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa-sign-out fa fa-fw"></i> <%= t(:sign_out) %>
                  <% end %>
                </li>
              </ul>
            </li>
          </ul>
          <!-- Left Nav Section -->
          <ul class="left">
            <li><%= link_to t(:new_ticket), new_ticket_path %></li>
          </ul>
        </section>
      </nav>
    <% end %>

    <div class="row collapse">
      <% if user_signed_in? %>
        <aside class="hide-for-small medium-3 large-2 columns">
          <ul class="off-canvas-list mt">
            <li>
              <%= active_elem_if :a, params[:status] == 'open' &&
                  params[:assignee_id].to_i == 0,
                  href: root_path do %>
                <span class="fa fa-inbox"></span><%= t(:inbox) %>
                <% if Ticket.open.count > 0 %>
                  <span class="regular round label"><%= Ticket.open.count %></label>
                <% end %>
              <% end %>
            </li>
            <li>
              <%= active_elem_if :a, params[:status] == 'open' &&
                  params[:assignee_id].to_i == current_user.id,
                  href: tickets_path(assignee_id: current_user.id) do %>
                <span class="fa fa-user"></span><%= t(:mine) %>
                <% if Ticket.where(assignee_id: current_user.id, status: 0).count > 0 %>
                  <span class="alert round label"><%= Ticket.where(assignee_id: current_user.id, status: 0).count %></span>
                <% end %>
              <% end %>
            </li>
            <li>
              <%= active_elem_if :a, params[:status] == 'waiting',
                  href: tickets_path(status: 'waiting') do %>
                <span class="fa fa-clock-o"></span><%= t(:waiting) %>
                <% if Ticket.where(assignee_id: current_user.id, status: 3).count > 0 %>
		  <span class="secondary round label"><%= Ticket.where(assignee_id: current_user.id, status: 3).count %></span>
		<% end %>
              <% end %>
            </li>
            <li>
              <%= active_elem_if :a, params[:status] == 'closed',
                   href: tickets_path(status: 'closed') do %>
                <span class="fa fa-check"></span><%= t(:closed_tickets) %>
              <% end %>
            </li>
            <li>
              <%= active_elem_if :a, params[:status] == 'deleted',
                  href: tickets_path(status: 'deleted') do %>
                <span class="fa fa-trash-o"></span><%= t(:trashed) %>
              <% end %>
            </li>
          </ul>

          <ul class="off-canvas-list">
            <li><label><%= t(:labels) %></label></li>
            <% @labels.each do |label| %>
              <%
                # toggle label on/off
                if params[:label_id].to_i == label.id
                  p = params.merge(label_id: nil)
                else
                  p = params.merge(label_id: label.id)
                end
              %>
              <li>
                <a href="<%= tickets_url(p) %>" class="<%= 'active ' if params[:label_id].to_i == label.id %>hover-icon-a">
                  <i class="fa fa-square" style="color: <%= label.color %>"></i>
                  <%= label.name %>
                  <i data-dropdown="label-<%= label.id %>" class="fa fa-cogs hover-icon"></i>
                </a>
                <ul id="label-<%= label.id %>" class="f-dropdown" data-dropdown-content>
                  <% Label::COLORS.each_with_index do |color, index| %>
                    <li>
                      <%= link_to label_path(label, color: index), method: :patch, remote: true do %>
                        <i class="fa fa-square" style="color: <%= color %>"></i>
                      <% end %>
                    </li>
                  <% end %>
                  <li>
                    <%= link_to label_path(label), method: :delete, data: { confirm: t(:are_you_sure) }, remote: true do %>
                      <%= fa_icon 'trash' %>
                    <% end %>
                  </li>
                </ul>
              </li>
            <% end %>
          </ul>
        </aside>
        <%# 100vh - 60px because top-bar height is 60px %>
        <div class="medium-9 large-10 columns" style="background: #fff; min-height: calc(100vh - 60px);" data-main>
      <% else %>
        <div class="medium-9 large-10 columns medium-centered large-centered">
      <% end %>

        <% if notice %>
          <div data-alert class="notification alert-box success"><%= notice %><a href="#" class="close">&times;</a></div>
        <% end %>
        <% if alert %>
          <div data-alert class="notification alert-box alert"><%= alert %><a href="#" class="close">&times;</a></div>
        <% end %>

        <%= yield %>

      </div>
    </div>

    <div class="reveal-modal" data-reveal>
      <article>
      </article>
      <a class="close-reveal-modal">&#215;</a>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'jquery.toastmessage' %>
    <%= javascript_include_tag 'jquery.datetimepicker' %>
    <%= javascript_include_tag 'jquery.showhide' %>
    
  </body>
</html>